version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  sender:
    build: .
    ports:
      - "9091:9091"
    depends_on:
      - rabbitmq